### ISSUE TITLE
Segmentation error on initial run 

### ISSUE THREAD

**Issue by jhaskinsPhD** [geoschem/Cloud-J#1]
Really great idea pulling this out on its own.  I followed the install instructions to create a run directory and ran the standalone executable using our same CMAKE compiler we use for GEOS-Chem and got a segmentation error right after ```Rayl 58    0.02    0.00   200.3  1.3304E-06``` in my log file. 

Any ideas how I might go about troubleshooting?

**Comment by lizziel** [comment]
Hi @jhaskinsPhD, so sorry no one saw this until now. Were you able to get it to work?

**Comment by jhaskinsPhD** [comment]
I didn't - just found a workaround for what I was trying to do with it.

**Comment by lizziel** [comment]
Could you report what compiler you are using, including version number?

**Comment by jhaskinsPhD** [comment]
I can do some digging next week & get back to you. I think I was using gfortran, but I'll have to confirm/check the version number next week post-AGU. We moved servers/compilers recently & I'm not actually sure if I was trying to do this on the new one or the old one...
