### ISSUE TITLE
How can get the interpolated results (e.g. addX_*.out file)？

### ISSUE THREAD

**Issue by ese-Liyl** [geoschem/Cloud-J#3]
Hello! I would like to implement cross-section interpolation for new species using Clould-J. Now I have created and generated the cloudj_standclone executable independently. How can I input the existing cross-sectional experimental data (e.g. addX_NF3.f file) into the ~/tables/ directory and run Could-J and get the interpolated results (e.g. addX_NF3.out file)?

**Comment by pratherUCI** [comment]
If you want to add a new photolysis cross section then you need to run AddX to calculate a Cloud-J table from the tabulated cross sections you have.  

Look up 'UCI_FJ_AddXs76.zip' as that has all the short, standalone codes that process from your tables to CL tables like below:

OCS   !OCS=>CO+S       ! OCS = carbonyl sulfide   JPL10
 200a 5.275E-20 3.879E-20 2.920E-20 2.343E-20 6.049E-20 1.232E-19 OCS
 200b 1.691E-19 2.181E-19 9.974E-21 4.126E-20 2.417E-20 9.292E-25 OCS
 200c 0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00 OCS
OCS   !                !
 300a 7.547E-20 5.314E-20 3.637E-20 2.436E-20 6.009E-20 1.222E-19 OCS
 300b 1.689E-19 2.186E-19 1.382E-20 4.616E-20 2.470E-20 3.294E-24 OCS
 300c 7.435E-26 0.000E+00 0.000E+00 0.000E+00 0.000E+00 0.000E+00 OCS

The formatting must be exact and you can add 2 different temperatures (or pressures) that the CJ code interpolates between (It does NOT extrapolate).  The zip file you can find on the github or else at my ftp site:  128.200.14.8/public/prather/Fast-J_&_Cloud-J/
Login in as anonymous.

This is NOT automatic, you must know what cross sections and quantum yields you have and revise the fortran codes to use them.  The integration and weighting over wavelength is  the core part and requires no effort from you, but the subroutines that calculate the cross sections can vary with species.  There are several different examples.

BTW, if you are doing NF3, then be careful about the quantum yield being less than 1.

Michael Prather

**Comment by Liyl2** [comment]
> 

OK,Thanks for your reply. @pratherUCI

**Comment by ese-Liyl** [comment]
OK,Thank you very much!

**Comment by yantosca** [comment]
We can close out this issue now as completed.
