### ISSUE TITLE
Ocean surface albedo module not used

### ISSUE THREAD

**Issue by lizziel** [geoschem/Cloud-J#7]
The GEOS-Chem implementation of Cloud-J does not use the ocean surface albedo module, instead using GMAO meteorology fields. The module is also not used in the Cloud-J standalone code, with reflectance values output by the module overwritten by LUT values (see [here](https://github.com/geoschem/Cloud-J/blob/85b78784a65ceed914f8a101ce6eb18c5c62681f/src/Interfaces/Standalone/CJ77.f90#L224-L226)).

@pratherUCI, could you comment on why it is not used in the standalone model and whether it is ready for use in other models? Would you be able to add documentation somewhere explaining the science, including references?

Tagging @mje1398

**Comment by mje1398** [comment]
Thanks @lizziel. 

Is it being overwritten with the UVALBEDO values read in from here: http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/UVALBEDO/v2019-06/ or from the A1 met fields from GMAO? 

https://wiki.seas.harvard.edu/geos-chem/index.php/List_of_GEOS-FP_met_fields seems to suggest that they aren't used in the photolysis code but this might be a typo? 

Mat

**Comment by lizziel** [comment]
In the standalone model the albedos are taken from [tables/atmos_PTClds.dat](https://github.com/geoschem/Cloud-J/blob/main/tables/atmos_PTClds.dat). This is simply 0.5 by default (see lines [here](https://github.com/geoschem/Cloud-J/blob/85b78784a65ceed914f8a101ce6eb18c5c62681f/tables/atmos_PTClds.dat#L4-L5)). Users would need to edit the file with the albedos they wish to use.

Yes, I was incorrect about the usage of albedo met-field in GEOS-Chem photolysis. There is a switch in `HEMCO_Config.rc` to read in offline UV albedo data and it is turned on in GEOS-Chem by default. The hourly meteorology (actually daily average due to met pre-processing) is visible band surface albedo and not UV, hence we use offline input in photolysis.
- Offline climatology UV albedo data stored [here](http://geoschemdata.wustl.edu/ExtData/HEMCO/UVALBEDO/v2019-06/). This data references a 1997 paper.
- Switch to use offline climatology [here](https://github.com/geoschem/geos-chem/blob/b288af1563a9a49a154a93bdd0f88be1f58f3f2f/run/GCClassic/HEMCO_Config.rc.templates/HEMCO_Config.rc.fullchem#L154)

**Comment by pratherUCI** [comment]
Hello, I think that Mat's question is already answered.  The OSA (ocean surface albedo) code is called in the standalone version to show how it is done (OSA is all _r4), the lataest standalone was used for other testing and so I just overwrote the albedo (for all wavelengths and all angles!, that is the new part) with 0.05 for dark ocean. The OSA code looks to be state-of-the-art, built by the French, but I had no equivalent for land.  

In general, ion the future, the albedo needs to be a function of wavelength and incident angle.

Michael P.

**Comment by pratherUCI** [comment]
Documentation/Publications:

OSA and code changes described in:
    Hsu, J.C. and M.J. Prather (2021), Assessing uncertainties and approximations in solar heating of the climate system. Journal of Advances in Modeling Earth Systems, 13, e2020MS002131. doi: 10.1029/2020MS002131
and
 Prather, M.J. and J.C. Hsu (2019) A round Earth for climate models, Proc Natl Acad Sci, 116 (39) 19330-19335; https://doi.org/10.1073/pnas.1908198116.

New Dryad repositories
  Prather, Michael and Hsu, Juno (2019), Solar-J and Cloud-J models version 7.6c, v2, UC Irvine Dash, Dataset, doi.org/10.7280/D1096P
  Hsu, Juno and Prather, Michael (2020), Data from: Errors in calculating solar heating of the climate system, v3, UC Irvine, Dataset, https://doi.org/10.7280/D1PQ3W
  Prather, Michael (2023). An updated cloud-overlap photolysis module for atmospheric chemistry models, UCI Cloud-J v8.0, with near-UV H2O absorption [Dataset]. Dryad. https://doi.org/10.7280/D1Q398
